const ACTION = {
  SEARCH_MODAL_SHOW: "SEARCH_MODAL_SHOW",
  SEARCH_MODAL_HIDE: "SEARCH_MODAL_HIDE",
  SET_BLOG_LENGTH: "SET_BLOG_LENGTH",
  SET_POSTS: "SET_POSTS",
  SET_FILTER_POSTS: "SET_FILTER_POSTS",
};

export default ACTION;
